// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/a-propos" | "/candidat" | "/candidat/candidatures" | "/candidat/candidatures/[slug]" | "/candidat/cv" | "/candidat/profil" | "/candidat/sauvegardes" | "/connexion" | "/deconnexion" | "/entreprises" | "/entreprises/[slug]" | "/inscription" | "/jobs/[slug]" | "/recruteur" | "/recruteur/candidats" | "/recruteur/candidats/[id]" | "/recruteur/candidats/ajouter" | "/recruteur/entreprise" | "/recruteur/equipe" | "/recruteur/magazine" | "/recruteur/offres" | "/recruteur/offres/[id]" | "/recruteur/offres/[id]/candidats" | "/recruteur/onboarding" | "/recruteur/publier" | "/reset-password" | "/stories" | "/stories/[slug]" | "/tarifs"
type AppRouteHandlerRoutes = "/api/ai/generate-job" | "/api/ai/generate-message" | "/api/ai/scan-company" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/a-propos": {}
  "/api/ai/generate-job": {}
  "/api/ai/generate-message": {}
  "/api/ai/scan-company": {}
  "/auth/callback": {}
  "/candidat": {}
  "/candidat/candidatures": {}
  "/candidat/candidatures/[slug]": { "slug": string; }
  "/candidat/cv": {}
  "/candidat/profil": {}
  "/candidat/sauvegardes": {}
  "/connexion": {}
  "/deconnexion": {}
  "/entreprises": {}
  "/entreprises/[slug]": { "slug": string; }
  "/inscription": {}
  "/jobs/[slug]": { "slug": string; }
  "/recruteur": {}
  "/recruteur/candidats": {}
  "/recruteur/candidats/[id]": { "id": string; }
  "/recruteur/candidats/ajouter": {}
  "/recruteur/entreprise": {}
  "/recruteur/equipe": {}
  "/recruteur/magazine": {}
  "/recruteur/offres": {}
  "/recruteur/offres/[id]": { "id": string; }
  "/recruteur/offres/[id]/candidats": { "id": string; }
  "/recruteur/onboarding": {}
  "/recruteur/publier": {}
  "/reset-password": {}
  "/stories": {}
  "/stories/[slug]": { "slug": string; }
  "/tarifs": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
