// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/a-propos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/a-propos">> = Specific
  const handler = {} as typeof import("../../../src/app/a-propos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/candidatures/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat/candidatures/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/candidatures/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/candidatures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat/candidatures">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/candidatures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/cv/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat/cv">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/cv/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/profil/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat/profil">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/profil/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/candidat/sauvegardes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/candidat/sauvegardes">> = Specific
  const handler = {} as typeof import("../../../src/app/candidat/sauvegardes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/connexion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connexion">> = Specific
  const handler = {} as typeof import("../../../src/app/connexion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/deconnexion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deconnexion">> = Specific
  const handler = {} as typeof import("../../../src/app/deconnexion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/entreprises/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entreprises/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/entreprises/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/entreprises/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entreprises">> = Specific
  const handler = {} as typeof import("../../../src/app/entreprises/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/inscription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inscription">> = Specific
  const handler = {} as typeof import("../../../src/app/inscription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/jobs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jobs/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/jobs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/candidats/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/candidats/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/candidats/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/candidats/ajouter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/candidats/ajouter">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/candidats/ajouter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/candidats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/candidats">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/candidats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/entreprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/entreprise">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/entreprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/equipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/equipe">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/equipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/magazine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/magazine">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/magazine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/offres/[id]/candidats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/offres/[id]/candidats">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/offres/[id]/candidats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/offres/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/offres/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/offres/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/offres/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/offres">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/offres/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/onboarding">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/recruteur/publier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recruteur/publier">> = Specific
  const handler = {} as typeof import("../../../src/app/recruteur/publier/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stories/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/stories/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/stories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories">> = Specific
  const handler = {} as typeof import("../../../src/app/stories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/tarifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tarifs">> = Specific
  const handler = {} as typeof import("../../../src/app/tarifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/generate-job/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-job">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/generate-job/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/generate-message/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/generate-message">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/generate-message/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ai/scan-company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/scan-company">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ai/scan-company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
